#pragma once

#define PROJECT_NAME "OPENGL_Plugin"
#define RELEASE_CHANNEL "a"
#define OPENGL_PLUGIN_VERSION_MAJOR 1
#define OPENGL_PLUGIN_VERSION_MINOR 0
#define OPENGL_PLUGIN_VERSION_PATCH 0
#define OPENGL_PLUGIN_VERSION_STRING "1.0.0:a"
